# Generated by Django 3.2.13 on 2022-06-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectorprofilemodel',
            name='collection_districts',
        ),
        migrations.RemoveField(
            model_name='collectorprofilemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='collectorprofilemodel',
            name='worked_items',
        ),
        migrations.RemoveField(
            model_name='consumerprofilemodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='collaboratorProfileModel',
        ),
        migrations.DeleteModel(
            name='CollectorProfileModel',
        ),
        migrations.DeleteModel(
            name='ConsumerProfileModel',
        ),
        migrations.DeleteModel(
            name='DistrictsModel',
        ),
        migrations.DeleteModel(
            name='ItemModel',
        ),
    ]
