# Generated by Django 3.2.13 on 2022-06-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='tipo',
            field=models.CharField(choices=[('coletor', 'Coletor'), ('consumidor', 'Consumidor'), ('colaborador', 'Colaborador')], default='colaborador', max_length=11, verbose_name='Tipo de usuário'),
        ),
        migrations.AlterField(
            model_name='coletor',
            name='tipo',
            field=models.CharField(choices=[('coletor', 'Coletor'), ('consumidor', 'Consumidor'), ('colaborador', 'Colaborador')], default='coletor', max_length=11, verbose_name='Tipo de usuário'),
        ),
    ]
