# Generated by Django 3.2.13 on 2022-06-02 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20220602_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.enderecomodel'),
        ),
        migrations.AlterField(
            model_name='coletor',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.enderecomodel'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.enderecomodel'),
        ),
    ]
