# Generated by Django 3.2.13 on 2022-06-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_remetente', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('status', models.BooleanField(default=False, verbose_name='Contato aberto')),
            ],
            options={
                'verbose_name': 'LPGD',
                'verbose_name_plural': 'LGPD',
            },
        ),
        migrations.CreateModel(
            name='ContatoSimples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_remetente', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('status', models.BooleanField(default=False, verbose_name='Status (contato aberto/contato não aberto)')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
